### ISSUE TITLE
Refactor the rules for ORDER BY and GROUP BY 

### ISSUE THREAD

**Issue by Zarquan** [ivoa/lyonetia#7]
In the current BNF the rules for ORDER BY and GROUP BY are different, and don't allow some complex constructs put forward by users.

Proposal is to change ORDER BY and GROUP BY to use the same rules, and expand the rules to allow column references, select fields, aliases and expressions in both ORDER BY and GROUP BY, with the caveat that the column reference, select field, aliase or expression must match a field from the SELECT list.

Using an alias defined in the SELECT list would be valid
```sql
    SELECT
        0.25*(0.5+FLOOR(LOG10(Mvir)/0.25)) AS log_mass,
        COUNT(*) AS num
    FROM
        MDR1.bdmv
    WHERE
        snapnum=85
    GROUP BY
        log_mass
    ORDER BY
        log_mass
```
Using an expression defined in the SELECT list would be valid
```sql
    SELECT
        0.25*(0.5+FLOOR(LOG10(Mvir)/0.25)) AS log_mass,
        COUNT(*) AS num
    FROM
        MDR1.bdmv
    WHERE
        snapnum=85
    GROUP BY
        0.25*(0.5+FLOOR(LOG10(Mvir)/0.25))
    ORDER BY
        0.25*(0.5+FLOOR(LOG10(Mvir)/0.25))

```
But using an expression that is not in the SELECT list would not be valid
```sql
    SELECT
        0.25*(0.5+FLOOR(LOG10(Mvir)/0.25)) AS log_mass,
        COUNT(*) AS num
    FROM
        MDR1.bdmv
    WHERE
        snapnum=85
    GROUP BY
        FLOOR(LOG10(Mvir)/0.25) -- This does not match a SELECT field
    ORDER BY
        FLOOR(LOG10(Mvir)/0.25) -- This does not match a SELECT field
```
In addition, the rules should be updated to allow both a long form fully qualified column reference, or, where it is unique within the context of the query, a short form column name.

For a column reference, using the fully qualified table name would be valid:
```sql
    SELECT
        TOP 10
        TAP_SCHEMA.columns.column_name
    FROM
        TAP_SCHEMA.columns
    ORDER BY
        TAP_SCHEMA.columns.column_name
 ```
Using the unqualified table name would be valid:
```sql
    SELECT
        TOP 10
        columns.column_name
    FROM
        TAP_SCHEMA.columns
    ORDER BY
        columns.column_name
 ```
Using a table alias would be valid:
```sql
    SELECT
        TOP 10
        cols.column_name
    FROM
        TAP_SCHEMA.columns AS cols
    ORDER BY
        cols.column_name
 ```
Using the short form column name would be valid, as long as it is unique within the context:
```sql
    SELECT
        TOP 10
        column_name
    FROM
        TAP_SCHEMA.columns
    ORDER BY
        column_name
 ```
.
However, in each of these cases, the column reference in the ORDER BY or GROUP by clause **MUST** match a column reference defined in the SELECT list.

Mixing the short and longs forms would not be valid :
```sql
    SELECT
        TOP 10
        column_name
    FROM
        TAP_SCHEMA.columns AS cols
    ORDER BY
        cols.column_name -- This does not match a SELECT field.
 ```
Mixing table name and table alias would not be valid :
```sql
    SELECT
        TOP 10
        columns.column_name
    FROM
        TAP_SCHEMA.columns AS cols
    ORDER BY
        cols.column_name -- This does not match a SELECT field.
 ```

**Comment by msdemlei** [comment]
Holy cow -- are there any database systems that really work like this?  In particular, requiring that entire expressions can be selected if the *expressions* are being grouped by seems extremely hard to define; does whitespace make expressions unequal? Reordering operands of commutative operators?

I'd say what you're proposing here can relatively easily be affected by using subqueries.  I'd maintain people want to learn about those anyway, so I don't think there's anything wrong with recommending them if people want to play tricks like these.

**Comment by Zarquan** [comment]
Markus is right - this proposal doesn't makes sense and I withdraw it. Apologies.
